project:
  type: website

website:
  title: "nbnav"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - file.name.ipynb
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
